### ISSUE TITLE
T13-1: Problem with restore command

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T13-1/main#125]
**Describe the bug**
Able to restore to previous state even though local copy of backup has been deleted.

**To Reproduce**
1. Go to the GUI
2. Enter the backup command
3. Find the preferences.json file in your Downloads folder
4. Delete the preferences.json file. 
5. Delete a person from the list [delete 1]
6. Enter restore command in the GUI
7. Watch the addressbook magically restore its contents back to the backup state

**Expected behavior**
If the local backup file (preferences.json) is deleted locally, the local restore command should not be able to restore the addressbook to the backup state.

<hr>

**Reported by:** @kangmingtay
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#690]</sub>

**Comment by QzSG** [comment]
1. You deleted the `preferences.json` file. But the whole point of Model Manager is that it has a copy of User Preferences in memory by design
2. Performing any operation after backup updates the memory model and commits the relevant books to storage.
3. Restore command does not reread from preferences file on every command. During an application runtime, updates to user preferences stay in memory state and only certain actions commit preferences to storage.
4. This is the expected behavior as when you delete the commited data books during runtime for example deleting `addressbook.xml`, do you expect the application to stop working after that if it is still running? If you do, that is a very bad example of MVC and poor application design in general. 
Reading a fresh copy of the files from storage and updating the model on every command incurs too much overhead and is not good practise
5. Why will a legit user delete preferences.json for fun while the application is running.
6. Bug described is not consistent with steps to reproduce. Have you tried deleting the local backup data file instead?

Therefore with the following points. @kangmingtay Please provide more information, that would help a lot

**Comment by QzSG** [comment]
Closed due to inactivity
